// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Veriado.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20251201083000_Fts5ContentlessUnified")]
partial class Fts5ContentlessUnified
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        new Snapshot().Build(modelBuilder);
#pragma warning restore 612, 618
    }

    private sealed class Snapshot : AppDbContextModelSnapshot
    {
        public void Build(ModelBuilder modelBuilder) => base.BuildModel(modelBuilder);
    }
}
