-- Legacy reference only. The authoritative FTS schema is defined in
-- SqliteFulltextSchemaSql.cs and applied via EF migrations.
--
-- This file is retained to document the historical structure of the
-- search_document and search_document_fts tables. It is no longer used
-- at runtime.
