// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Veriado.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250927230000_SearchEnhancements")]
    partial class SearchEnhancements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            new SnapshotProxy().Populate(modelBuilder);
        }

        private sealed class SnapshotProxy : AppDbContextModelSnapshot
        {
            public void Populate(ModelBuilder modelBuilder) => base.BuildModel(modelBuilder);
        }
    }
}
